server:
  port: 9000


spring:
  application:
    name: api-gateway

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 设置对外的访问路径
zuul:
  routes:
#    里面是用一个map存储的, 后面的会覆盖签名的
    product-service: /apigateway/product/**
    order-service: /apigateway/order/**
  sensitive-Headers:
#    默认是Cookie是拿不到的, 但是通过下面的设置可以获取得到
#  需求 ：不想让默认的服务对外暴露接口
#  /order-service/api/v1/order/save
  ignored-patterns:  /*-service/api/v1/**

#  下面不会怎么用, 一般都是用上面的
  #  ignored-services: product-service
#    ignored-services: order-service