server:
  port: 9000


spring:
  application:
    name: api-gateway

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 设置对外的访问路径
zuul:
  routes:
#    product-service: /admingateway/**
    order-service: /apigateway/**
#  需求 ：不想让默认的服务对外暴露接口
#  /order-service/api/v1/order/save
    ignored-patterns:  /*-service/api/v1/**
#  下面不会怎么用, 一般都是用上面的
#  ignored-services: product-service
#    ignored-services: order-service