server:
  port: 8781

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 服务名称
spring:
  application:
    name: order-service
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 2000
  zipkin:
    base-url: http://192.168.1.49:9411/

# 定义规则
product-service:
    ribbon:
      # 随机的, 也可以设置权重的WeightedResponseTimeRule
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


# 即使内容提供者设置了1s, 但是由于熔断器Hystrix的原因(默认时间为1s), 所以也会请求超时
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
#        一般设置2s
        connectTimeout: 4000
#        一般设置2s
        readTimeout: 4000


#hystrix: 关闭超时时间(不推荐使用)
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false

#  设置超时时间(推荐使用)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

# 监控接口请求情况
management:
  endpoints:
    web:
      exposure:
        include: "*"